version: '3.3'

services:

  app:
    image: docker.io/hoto/test-s3
    restart: always
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    ports:
      - 8081:8080
